spring: 
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/linebot
#      username: root
#      password: root
      authentication-database: admin
line.bot:
    channel-token: <your channel token>
    channel-secret: <your channel secret>
    handler:
      path: /callback
      enabled: true

weather.api.key: 
